const mockDate = (value) => value;

export const mockPlatforms = [
  { id: 167, name: "PlayStation 5", slug: "ps5", abbreviation: "PS5" },
  { id: 169, name: "Xbox Series X|S", slug: "xbox-series", abbreviation: "XSX" },
  { id: 6, name: "PC (Microsoft Windows)", slug: "pc", abbreviation: "PC" },
  { id: 130, name: "Nintendo Switch", slug: "switch", abbreviation: "NS" },
];

function buildGame({
  id,
  name,
  summary,
  storyline,
  cover,
  website,
  genres,
  modes,
  developer,
  publisher,
  rating,
  hypes,
  date,
  platform,
}) {
  return {
    id,
    name,
    summary,
    storyline,
    cover: cover ? { url: cover } : null,
    artworks: [],
    videos: [],
    websites: website ? [{ url: website }] : [],
    genres: genres.map((entry, index) => ({ id: id * 10 + index, name: entry })),
    game_modes: modes.map((entry, index) => ({ id: id * 100 + index, name: entry })),
    developer: developer ? [{ id: id * 1000 + 1, name: developer }] : [],
    publisher: publisher ? [{ id: id * 1000 + 2, name: publisher }] : [],
    total_rating: rating,
    hypes,
    date: mockDate(date),
    platform,
  };
}

export const mockGames = [
  buildGame({
    id: 101,
    name: "Glass Circuit",
    summary: "A tactical racing game about speed, sabotage, and neon city weather.",
    storyline: "Rogue teams fight for control of the last legal anti-grav circuit.",
    cover: "/mock-covers/glass-circuit.svg",
    website: "https://store.steampowered.com/",
    genres: ["Racing", "Strategy"],
    modes: ["Single player", "Multiplayer"],
    developer: "Orbital Frame",
    publisher: "Northline",
    rating: 84,
    hypes: 93,
    date: "2026-06-02",
    platform: mockPlatforms[0],
  }),
  buildGame({
    id: 102,
    name: "Wasteland Keeper",
    summary: "Build a caravan fortress and survive shifting factions in a radioactive desert.",
    storyline: "Your convoy carries the last living seed bank across a collapsing republic.",
    cover: "/mock-covers/wasteland-keeper.svg",
    website: "https://www.playstation.com/",
    genres: ["RPG", "Adventure"],
    modes: ["Co-operative"],
    developer: "Dust Choir",
    publisher: "Axiom Shelter",
    rating: 79,
    hypes: 145,
    date: "2026-06-04",
    platform: mockPlatforms[0],
  }),
  buildGame({
    id: 103,
    name: "Pine Harbor FC",
    summary: "A management sim where morale, weather, and local politics matter as much as tactics.",
    storyline: "Save a seaside club from relegation and turn it into a continental force.",
    cover: "/mock-covers/pine-harbor-fc.svg",
    website: "https://www.xbox.com/",
    genres: ["Simulator", "Sport"],
    modes: ["Single player"],
    developer: "Pierlight",
    publisher: "Morrow Games",
    rating: 73,
    hypes: 57,
    date: "2026-06-07",
    platform: mockPlatforms[1],
  }),
  buildGame({
    id: 104,
    name: "Signal of the Deep",
    summary: "First-person investigation aboard a research vessel that should not exist anymore.",
    storyline: "Decoded sonar logs lead you beneath a quarantined trench.",
    cover: "/mock-covers/signal-of-the-deep.svg",
    website: "https://www.nintendo.com/",
    genres: ["Horror", "Puzzle"],
    modes: ["Single player"],
    developer: "Mareline",
    publisher: "Blue Trestle",
    rating: 88,
    hypes: 166,
    date: "2026-06-09",
    platform: mockPlatforms[3],
  }),
  buildGame({
    id: 105,
    name: "Patch Zero",
    summary: "A co-op extraction shooter about corrupted maintenance tunnels under a megacity.",
    storyline: "Recover black-box archives before the grid seals entire districts forever.",
    cover: "/mock-covers/patch-zero.svg",
    website: "https://store.steampowered.com/",
    genres: ["Shooter"],
    modes: ["Multiplayer", "Co-operative"],
    developer: "Latchkey",
    publisher: "Tangent House",
    rating: 0,
    hypes: 121,
    date: "2026-06-11",
    platform: mockPlatforms[2],
  }),
  buildGame({
    id: 106,
    name: "Ashen Relay",
    summary: "Escort trains through a civil war where every station is a negotiation.",
    storyline: "A radio operator becomes the only neutral courier between collapsing cities.",
    cover: "/mock-covers/wasteland-keeper.svg",
    website: "https://store.steampowered.com/",
    genres: ["Strategy", "Narrative"],
    modes: ["Single player"],
    developer: "Low Beacon",
    publisher: "Galehouse",
    rating: 81,
    hypes: 64,
    date: "2026-06-13",
    platform: mockPlatforms[2],
  }),
  buildGame({
    id: 107,
    name: "Velvet Tactics",
    summary: "Plan impossible heists in a city that rebuilds itself each night.",
    storyline: "A disgraced detective assembles a crew to rob the archive that erased her past.",
    cover: "/mock-covers/glass-circuit.svg",
    website: "https://www.playstation.com/",
    genres: ["Tactical", "Stealth"],
    modes: ["Single player"],
    developer: "Cinder Loop",
    publisher: "Northline",
    rating: 86,
    hypes: 175,
    date: "2026-06-15",
    platform: mockPlatforms[0],
  }),
  buildGame({
    id: 108,
    name: "Harborline Stories",
    summary: "A slice-of-life mystery set across ferries, markets, and storm shelters.",
    storyline: "Each route reveals another witness to the disappearance of the harbor master.",
    cover: "/mock-covers/pine-harbor-fc.svg",
    website: "https://www.nintendo.com/",
    genres: ["Adventure", "Visual Novel"],
    modes: ["Single player"],
    developer: "Murmur Street",
    publisher: "Blue Trestle",
    rating: 77,
    hypes: 38,
    date: "2026-06-17",
    platform: mockPlatforms[3],
  }),
  buildGame({
    id: 109,
    name: "Rift Department",
    summary: "An action RPG about sealing dimensional accidents in office towers.",
    storyline: "Your promotion came with a keycard, a sword, and no explanation.",
    cover: "/mock-covers/patch-zero.svg",
    website: "https://www.xbox.com/",
    genres: ["Action RPG"],
    modes: ["Single player", "Co-operative"],
    developer: "Vault Meridian",
    publisher: "Axiom Shelter",
    rating: 90,
    hypes: 209,
    date: "2026-06-19",
    platform: mockPlatforms[1],
  }),
  buildGame({
    id: 110,
    name: "Tidebreak Atlas",
    summary: "Chart an ocean that rewrites its islands after every eclipse.",
    storyline: "An ex-cartographer returns to the sea after receiving a map drawn in her own hand.",
    cover: "/mock-covers/signal-of-the-deep.svg",
    website: "https://store.steampowered.com/",
    genres: ["Exploration", "Survival"],
    modes: ["Single player"],
    developer: "Wake Thread",
    publisher: "Morrow Games",
    rating: 82,
    hypes: 111,
    date: "2026-06-21",
    platform: mockPlatforms[2],
  }),
  buildGame({
    id: 111,
    name: "Crown of Static",
    summary: "A rhythm-action campaign staged inside pirate television broadcasts.",
    storyline: "Hijack the signal, recruit rogue hosts, and turn feedback into a weapon.",
    cover: "/mock-covers/glass-circuit.svg",
    website: "https://www.playstation.com/",
    genres: ["Rhythm", "Action"],
    modes: ["Single player"],
    developer: "Stereo Lantern",
    publisher: "Tangent House",
    rating: 76,
    hypes: 52,
    date: "2026-06-23",
    platform: mockPlatforms[0],
  }),
  buildGame({
    id: 112,
    name: "Ghostline Courier",
    summary: "Deliver contraband memories through a city where roads exist only at night.",
    storyline: "A courier discovers one of the packages contains her erased childhood.",
    cover: "/mock-covers/wasteland-keeper.svg",
    website: "https://www.xbox.com/",
    genres: ["Action", "Adventure"],
    modes: ["Single player"],
    developer: "Hinterglass",
    publisher: "Northline",
    rating: 83,
    hypes: 142,
    date: "2026-06-25",
    platform: mockPlatforms[1],
  }),
  buildGame({
    id: 113,
    name: "Lantern Protocol",
    summary: "An immersive sim about infiltrating a climate-controlled arcology.",
    storyline: "You were sent to steal one blueprint and found a city-sized experiment.",
    cover: "/mock-covers/patch-zero.svg",
    website: "https://store.steampowered.com/",
    genres: ["Immersive Sim", "Stealth"],
    modes: ["Single player"],
    developer: "Latchkey",
    publisher: "Galehouse",
    rating: 89,
    hypes: 188,
    date: "2026-06-27",
    platform: mockPlatforms[2],
  }),
  buildGame({
    id: 114,
    name: "Northwind Ritual",
    summary: "A co-op survival game in a forest that rearranges itself around your campfire.",
    storyline: "Every dawn removes one trail and opens another deeper into the snowline.",
    cover: "/mock-covers/signal-of-the-deep.svg",
    website: "https://www.nintendo.com/",
    genres: ["Survival", "Horror"],
    modes: ["Co-operative"],
    developer: "Mareline",
    publisher: "Blue Trestle",
    rating: 0,
    hypes: 72,
    date: "2026-06-29",
    platform: mockPlatforms[3],
  }),
  buildGame({
    id: 115,
    name: "Redline Echo",
    summary: "Sprint across orbital scrapyards while patching your ship mid-race.",
    storyline: "A suspended pilot joins a black-market circuit to repay an impossible debt.",
    cover: "/mock-covers/glass-circuit.svg",
    website: "https://store.steampowered.com/",
    genres: ["Racing", "Arcade"],
    modes: ["Single player", "Multiplayer"],
    developer: "Orbital Frame",
    publisher: "Northline",
    rating: 80,
    hypes: 99,
    date: "2026-07-03",
    platform: mockPlatforms[2],
  }),
  buildGame({
    id: 116,
    name: "Museum of Rain",
    summary: "Restore impossible exhibits while a permanent storm floods the city below.",
    storyline: "A conservator uncovers a collection that records disasters before they happen.",
    cover: "/mock-covers/pine-harbor-fc.svg",
    website: "https://www.playstation.com/",
    genres: ["Puzzle", "Adventure"],
    modes: ["Single player"],
    developer: "Murmur Street",
    publisher: "Axiom Shelter",
    rating: 85,
    hypes: 134,
    date: "2026-07-11",
    platform: mockPlatforms[0],
  }),
];

export function getMockPlatforms(platformIds = []) {
  if (!platformIds.length) {
    return mockPlatforms;
  }

  return mockPlatforms.filter((platform) => platformIds.includes(platform.id));
}

export function getMockGames({
  startDate,
  endDate,
  platformIds = [],
  minHype = 0,
  withRating = false,
}) {
  return mockGames.filter((game) => {
    const inRange = game.date >= startDate && game.date <= endDate;
    const inPlatform = !platformIds.length || platformIds.includes(game.platform.id);
    const inHype = game.hypes >= minHype;
    const hasRating = !withRating || game.total_rating > 0;

    return inRange && inPlatform && inHype && hasRating;
  });
}
